### PR TITLE
[type:fix] fix trie match error

### LINKED ISSUE #4513: Rule closing does not take effect
### Question

When the selector rule is closed and the interface is requested, the closed selector rule will still be matched
image
image
image

### PR DESCRIPTION
**Pull request by moremind**
fixes #4513 and #4511

Make sure that:

- [ ] You have read the [contribution guidelines](https://shenyu.apache.org/community/contributor-guide).
- [ ] You submit test cases (unit or integration tests) that back your changes.
- [ ] Your local test passed `./mvnw clean install -Dmaven.javadoc.skip=true`.

### CODE REVIEW

File: shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/RuleServiceImpl.java [hunk 1]
```diff
@@ -154,8 +155,26 @@ public int update(final RuleDTO ruleDTO) {
...
+                        .build()).collect(Collectors.toList());
+        List<RuleConditionDTO> currentRuleCondition = ruleDTO.getRuleConditions().stream().map(ruleConditionDTO ->
+                RuleConditionDTO.builder()
+                        .ruleId(ruleConditionDTO.getRuleId())
+                        .operator(ruleConditionDTO.getOperator())
+                        .paramName(ruleConditionDTO.getParamName())
+                        .paramType(ruleConditionDTO.getParamType())
+                        .paramValue(ruleConditionDTO.getParamValue())
+                        .build()).collect(Collectors.toList());
+        if (CollectionUtils.isEqualCollection(beforRuleCondition, currentRuleCondition)) {
```
Comment (damonxue) [inline shenyu-admin/src/main/java/org/apache/shenyu/admin/service/impl/RuleServiceImpl.java:175]: Maybe `beforeRuleDtos` and `currentRuleDtos` are more clear than (`beforRuleCondition` vs 'beforeRuleCondition')

**Comment by damonxue** [comment]
(●'◡'●) Maybe `beforeRuleDtos` and `currentRuleDtos` are more clear than (`beforRuleCondition` vs `beforeRuleCondition`)

**Comment by moremind** [comment]
> (●'◡'●) Maybe `beforeRuleDtos` and `currentRuleDtos` are more clear than (`beforRuleCondition` vs `beforeRuleCondition`)

I think just compare with before rule condition, because, we use rule condition build shenyu trie. This is just a update operator.

**Review by yu199195 — APPROVED** [review]
