### PR TITLE
[type:BUG] hystrix plugin can't circuitBreaker.

### LINKED ISSUE #3820: [BUG] hystrix plugin can't circuitBreaker
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have config rule in rule No.1, and I change executionIsolationStrategy semaphore and thread, but I change from semaphore to thread, hystrix pluign can't circuitBreaker, this need restart or delete this rule and reconfig can circuitBreaker?

### Expected Behavior

change rule in same rule, can circuitBreaker.

### Steps To Reproduce

_No response_

### Environment

```markdown
ShenYu version(s):2.5.0
```

### Debug logs

 [WebSocketConnectReadThread-262] INFO  org.apache.shenyu.plugin.sync.data.websocket.client.ShenyuWebsocketClient - handleResult({"groupType":"RULE","eventType":"UPDATE","data":[{"id":"1556813932145938432","name":"/http/test/**","pluginName":"hystrix","selectorId":"1556813671167954944","matchMode":0,"sort":1,"enabled":true,"loged":true,"handle":"{\"requestVolumeThreshold\":\"5\",\"errorThresholdPercentage\":\"5\",\"sleepWindowInMilliseconds\":\"50000\",\"executionIsolationStrategy\":0,\"callBackUri\":\"\",\"groupKey\":\"\",\"commandKey\":\"\",\"hystrixThreadPoolConfig\":{\"coreSize\":10,\"maximumSize\":10,\"maxQueueSize\":12}}","conditionDataList":[{"paramType":"uri","operator":"startsWith","paramName":"/","paramValue":"/http/"}]}]})

[WebSocketConnectReadThread-262] INFO  org.apache.shenyu.plugin.sync.data.websocket.client.ShenyuWebsocketClient - handleResult({"groupType":"RULE","eventType":"UPDATE","data":[{"id":"1556813932145938432","name":"/http/test/**","pluginName":"hystrix","selectorId":"1556813671167954944","matchMode":0,"sort":1,"enabled":true,"loged":true,"handle":"{\"requestVolumeThreshold\":\"5\",\"errorThresholdPercentage\":\"5\",\"sleepWindowInMilliseconds\":\"50000\",\"executionIsolationStrategy\":1,\"callBackUri\":\"\",\"groupKey\":\"\",\"commandKey\":\"\",\"maxConcurrentRequests\":\"0\"}","conditionDataList":[{"paramType":"uri","operator":"startsWith","paramName":"/","paramValue":"/http/"}]}]})

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by yunlongn**
Fixes #3820

Make sure that:

- [ ] You have read the [contribution guidelines](https://shenyu.apache.org/community/contributor-guide).
- [ ] You submit test cases (unit or integration tests) that back your changes.
- [ ] Your local test passed `./mvnw clean install -Dmaven.javadoc.skip=true`.

### CODE REVIEW

File: shenyu-plugin/shenyu-plugin-hystrix/src/main/java/org/apache/shenyu/plugin/hystrix/HystrixPlugin.java [hunk 1]
```diff
@@ -53,7 +54,9 @@ public class HystrixPlugin extends AbstractShenyuPlugin {
     protected Mono<Void> doExecute(final ServerWebExchange exchange, final ShenyuPluginChain chain, final SelectorData selector, final RuleData rule) {
         final ShenyuContext shenyuContext = exchange.getAttribute(Constants.CONTEXT);
         assert shenyuContext != null;
-        final HystrixHandle hystrixHandle = HystrixPluginDataHandler.CACHED_HANDLE.get().obtainHandle(CacheKeyUtils.INST.getKey(rule));
+        final HystrixHandle hystrixHandle = new HystrixHandle();
+        // Avoid modifying objects in the cache
+        BeanUtils.copyProperties(HystrixPluginDataHandler.CACHED_HANDLE.get().obtainHandle(CacheKeyUtils.INST.getKey(rule)), hystrixHandle);
```
Comment (yu199195) [inline shenyu-plugin/shenyu-plugin-hystrix/src/main/java/org/apache/shenyu/plugin/hystrix/HystrixPlugin.java]: why need used BeanUtils.copyPropertie？

Comment (yunlongn) [reply shenyu-plugin/shenyu-plugin-hystrix/src/main/java/org/apache/shenyu/plugin/hystrix/HystrixPlugin.java]: because the following `hystrixHandle.setGroupKey` will modify the data in the cache, causing other errors.

Comment (yunlongn) [reply shenyu-plugin/shenyu-plugin-hystrix/src/main/java/org/apache/shenyu/plugin/hystrix/HystrixPlugin.java]: maybe my current commit can solve the problem another way.

Comment (yu199195) [reply shenyu-plugin/shenyu-plugin-hystrix/src/main/java/org/apache/shenyu/plugin/hystrix/HystrixPlugin.java]: Hi， in  shenyu-admin， Is the groupKey configured?

Comment (yunlongn) [reply shenyu-plugin/shenyu-plugin-hystrix/src/main/java/org/apache/shenyu/plugin/hystrix/HystrixPlugin.java]: yes 
image

**Review by yu199195 — APPROVED** [review]
