### PR TITLE
[ISSUE #4399]  check rule uri condition on save.

### LINKED ISSUE #4399: [Task] verification of rule correctness.
### Question

When a rule is added, it is expected to perform basic validation of the rule to avoid errors.

I think this is a very meaningful optimization, and willing to complete it, please review it, and if it passes, please assign it to me

For example:

image

Visit error:

image

Task
- implement validation logic

### PR DESCRIPTION
**Pull request by iwangjie**
fix #4399 

image

Make sure that:

- [ ] You have read the [contribution guidelines](https://shenyu.apache.org/community/contributor-guide).
- [ ] You submit test cases (unit or integration tests) that back your changes.
- [ ] Your local test passed `./mvnw clean install -Dmaven.javadoc.skip=true`.

### CODE REVIEW

File: shenyu-admin/src/main/java/org/apache/shenyu/admin/service/RuleService.java [hunk 1]
```diff
@@ -48,6 +53,18 @@ public interface RuleService extends PageService<RuleQueryCondition, RuleVO> {
      * @return rows int
      */
     default int createOrUpdate(final RuleDTO ruleDTO) {
+        // check rule uri condition
+        try {
+            final List<RuleConditionDTO> ruleConditions = ruleDTO.getRuleConditions();
+            List<RuleConditionDTO> filterConditions = ruleConditions.stream()
+                    .filter(conditionData -> ParamTypeEnum.URI.getName().equals(conditionData.getParamType()))
+                    .collect(Collectors.toList());
```
Comment (damonxue) [inline shenyu-admin/src/main/java/org/apache/shenyu/admin/service/RuleService.java:61]: .map(RuleConditionDTO::getParamValue).collect(Collectors.toList());

File: shenyu-admin/src/main/java/org/apache/shenyu/admin/service/RuleService.java [hunk 2]
```diff
@@ -48,6 +53,18 @@ public interface RuleService extends PageService<RuleQueryCondition, RuleVO> {
      * @return rows int
      */
     default int createOrUpdate(final RuleDTO ruleDTO) {
+        // check rule uri condition
+        try {
+            final List<RuleConditionDTO> ruleConditions = ruleDTO.getRuleConditions();
+            List<RuleConditionDTO> filterConditions = ruleConditions.stream()
+                    .filter(conditionData -> ParamTypeEnum.URI.getName().equals(conditionData.getParamType()))
```
Comment (damonxue) [inline shenyu-admin/src/main/java/org/apache/shenyu/admin/service/RuleService.java:60]: `.map(RuleConditionDTO::getParamValue).collect(Collectors.toList());` One stream replace.

File: shenyu-admin/src/main/java/org/apache/shenyu/admin/service/RuleService.java [hunk 3]
```diff
@@ -48,6 +53,17 @@ public interface RuleService extends PageService<RuleQueryCondition, RuleVO> {
      * @return rows int
      */
     default int createOrUpdate(final RuleDTO ruleDTO) {
+        // check rule uri condition
+        try {
+            final List<RuleConditionDTO> ruleConditions = ruleDTO.getRuleConditions();
+            List<String> uriPaths = ruleConditions.stream()
+                    .filter(conditionData -> ParamTypeEnum.URI.getName().equals(conditionData.getParamType()))
+                    .map(RuleConditionDTO::getParamValue)
+                    .collect(Collectors.toList());
```
Comment (damonxue) [inline shenyu-admin/src/main/java/org/apache/shenyu/admin/service/RuleService.java:62]: `.forEach(PathPatternParser.defaultInstance::parse);`
`collect()` is not needed.

**Comment by damonxue** [comment]
It's not a review, just suggest. @iwangjie ( ﹁ ﹁ ) ~→

**Comment by iwangjie** [comment]
> 



> It's not a review, just suggest. @iwangjie ( ﹁ ﹁ ) ~→

😉Thank you for your patience.

**Review by li-keguo — APPROVED** [review]

File: shenyu-admin/src/main/java/org/apache/shenyu/admin/service/RuleService.java [hunk 4]
```diff
@@ -48,6 +52,16 @@ public interface RuleService extends PageService<RuleQueryCondition, RuleVO> {
      * @return rows int
      */
     default int createOrUpdate(final RuleDTO ruleDTO) {
+        // check rule uri condition
+        try {
```
[the remark this answers is not in the document]
Comment (iwangjie) [reply shenyu-admin/src/main/java/org/apache/shenyu/admin/service/RuleService.java:56]: > 

Good Idea. I'll try.

[the remark this answers is not in the document]
Comment (iwangjie) [reply shenyu-admin/src/main/java/org/apache/shenyu/admin/service/RuleService.java:56]: Hi, I took a look, because RuleConditionDTO is not just a URL rule, there will be other things, so it may not be easy to add validation on a field, do you have a good idea?
