### PR TITLE
fix issue: only one cookie in request should can be removed if you want

### LINKED ISSUE #4007: [BUG] <title>RequestPlugin Remove Cookie
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If there is only one cookie at a reques, I can‘t remove it when I want to；
Because the code judges that only when the return cookie is not empty, it will be updated

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Environment

```markdown
ShenYu version(s):
```

### Debug logs

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by pandaapo**
Fixes #4007

Make sure that:x

- [x] You have read the [contribution guidelines](https://shenyu.apache.org/community/contributor-guide).
- [ ] You submit test cases (unit or integration tests) that back your changes.
- [ ] Your local test passed `./mvnw clean install -Dmaven.javadoc.skip=true`.

### CODE REVIEW

File: shenyu-plugin/shenyu-plugin-request/src/main/java/org/apache/shenyu/plugin/request/RequestPlugin.java [hunk 1]
```diff
@@ -93,8 +93,8 @@ public String named() {
     private void setHeaders(final HttpHeaders headers, final ServerHttpRequest request, final RequestHandle requestHandle) {
         List<HttpCookie> cookies = getCookies(request, requestHandle).values().stream()
                 .flatMap(Collection::stream).collect(Collectors.toList());
+        headers.remove(HttpHeaders.COOKIE);
```
Comment (yu199195) [inline shenyu-plugin/shenyu-plugin-request/src/main/java/org/apache/shenyu/plugin/request/RequestPlugin.java:96]: why modify this？

**Review by yu199195 — APPROVED** [review]
