### PR TITLE
[type:fix] Fix Plugin Edit Page Issue by Correcting Plugin ID Query and Updating Data Type

### LINKED ISSUE #5621: [BUG] Unable to Open Plugin Edit Page Due to Incorrect Plugin ID Query
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When attempting to open the plugin edit page in the ShenYu dashboard, the page fails to load. The root cause is an incorrect query where the GET /namespacePlugin/id={id}&namespaceId={namespaceId} request uses pluginId = {id} for querying. This results in no data being found. Additionally, the plugin_id field in the plugin_ns_rel table needs to be changed from a numeric type to VARCHAR(128) to avoid type mismatch errors.

### Expected Behavior

The plugin edit page should load successfully when clicking "Edit," retrieving the correct plugin data using the appropriate pluginId.

### Steps To Reproduce

1. In the ShenYu dashboard, navigate to the Plugin page.
2. Click the "Edit" button for any existing plugin.
3. Observe that the page fails to load.

### Environment

```markdown
ShenYu version(s): branch master latest
```

### Debug logs

_No response_

### Anything else?

This issue may relate to recent changes in the namespace feature. Additionally, the bulk operations such as delete and enable/disable still use id as the query condition.

### PR DESCRIPTION
**Pull request by VampireAchao**
Fixes #5621 

Fixes the issue where the plugin edit page fails to load due to an incorrect query in the `GET /namespacePlugin/id={id}&namespaceId={namespaceId}` endpoint. The query used `pluginId = {id}`, which resulted in no data being returned.

**Changes Made:**
- **Refactored**: `org.apache.shenyu.admin.service.NamespacePluginService#findById` to `findByPluginId`.
- **Updated**: The frontend request for "namespacePlugin/fetchItem" to use `pluginId` instead of `id`.
- **Modified**: The `plugin_id` field in the `plugin_ns_rel` table from a numeric type to `VARCHAR(128)` to prevent type mismatch errors.
- **Updated**: `org.apache.shenyu.admin.mapper.NamespacePluginRelMapper#existed` to align with the changes in how plugin IDs are handled.

Note that bulk operations such as delete and enable/disable still use `id` as the query condition. This PR may have implications for recent changes in the namespace feature. CC: @xcsnx

Make sure that:

- [x] You have read the [contribution guidelines](https://shenyu.apache.org/community/contributor-guide).
- [x] You submit test cases (unit or integration tests) that back your changes.
- [x] Your local test passed `./mvnw clean install -Dmaven.javadoc.skip=true`.

### CODE REVIEW

File: shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/NamespacePluginController.java [hunk 1]
```diff
@@ -103,16 +103,16 @@ public ShenyuAdminResult queryAllPlugins(@PathVariable("namespaceId")
      * detail plugin of namespace.
      *
      * @param namespaceId namespace id.
-     * @param id          id.
+     * @param pluginId    pluginId.
      * @return {@linkplain ShenyuAdminResult}
      */
-    @GetMapping("/id={id}&namespaceId={namespaceId}")
+    @GetMapping("/pluginId={pluginId}&namespaceId={namespaceId}")
```
Comment (moremind) [inline shenyu-admin/src/main/java/org/apache/shenyu/admin/controller/NamespacePluginController.java:109]: use `@GetMapping("/{id}/{namespaceId}")`

**Review by moremind — CHANGES_REQUESTED** [review]

**Review by moremind — APPROVED** [review]
