### PR TITLE
[type:fix] Fix the wrong request type

### LINKED ISSUE #4974: [BUG] Wrong request type in admin
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Test the swagger interface in the admin web page  
**The correct request parameters, but the response 415 exception**

### Expected Behavior

Expect the correct 200 response

### Steps To Reproduce

1. Clone shenyu master  
2. Start admin in IDEA  
3. Start bootstrap in IDEA  
4. Start shenyu-examples-http-swagger2 in IDEA  
5. Test the swagger interface in the admin web page  
   

### Environment

```markdown
ShenYu version(s): master
```

### Debug logs

in admin:
```
2023-08-09 13:59:06 [http-nio-0.0.0.0-9095-exec-7] INFO  org.apache.shenyu.admin.service.impl.SandboxServiceImpl - Sandbox Request Headers. toMap={"Content-Type":"application/json"}
2023-08-09 13:59:06 [http-nio-0.0.0.0-9095-exec-7] INFO  org.apache.shenyu.admin.service.impl.SandboxServiceImpl - sandbox Request Params. toMap={}
```
in bootstrap:
```
2023-08-09 13:59:06 [shenyu-netty-nio-7] INFO  org.apache.shenyu.plugin.base.AbstractShenyuPlugin - contextPath selector match success from default strategy
2023-08-09 13:59:06 [shenyu-netty-nio-7] INFO  org.apache.shenyu.plugin.base.AbstractShenyuPlugin - contextPath selector success match , selector name :/http-swagger2
2023-08-09 13:59:06 [shenyu-netty-nio-7] INFO  org.apache.shenyu.plugin.base.AbstractShenyuPlugin - contextPath rule match path from default strategy
2023-08-09 13:59:06 [shenyu-netty-nio-7] INFO  org.apache.shenyu.plugin.base.AbstractShenyuPlugin - contextPath rule success match , rule name :/http-swagger2
2023-08-09 13:59:06 [shenyu-netty-nio-7] INFO  org.apache.shenyu.plugin.base.AbstractShenyuPlugin - divide selector match success from default strategy
2023-08-09 13:59:06 [shenyu-netty-nio-7] INFO  org.apache.shenyu.plugin.base.AbstractShenyuPlugin - divide selector success match , selector name :/http-swagger2
2023-08-09 13:59:06 [shenyu-netty-nio-7] INFO  org.apache.shenyu.plugin.base.AbstractShenyuPlugin - divide rule match path from default strategy
2023-08-09 13:59:06 [shenyu-netty-nio-7] INFO  org.apache.shenyu.plugin.base.AbstractShenyuPlugin - divide rule success match , rule name :/http-swagger2/order/save
```
in shenyu-examples-http-swagger2:
```
2023-08-09 13:59:06.439  WARN 21332 --- [0.0-8190-exec-5] .w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.web.HttpMediaTypeNotSupportedException: Content type 'application/x-www-form-urlencoded;charset=UTF-8' not supported]
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by kerwin612**
Fixes #4974

Make sure that:
- [x] You have read the [contribution guidelines](https://shenyu.apache.org/community/contributor-guide).
- [ ] You submit test cases (unit or integration tests) that back your changes.
- [x] Your local test passed `./mvnw clean install -Dmaven.javadoc.skip=true`.

### CODE REVIEW

File: shenyu-admin/src/main/java/org/apache/shenyu/admin/utils/HttpUtils.java [hunk 1]
```diff
@@ -215,20 +215,18 @@ public String request(final String url, final Map<String, ?> form, final Map<Str
      * @return String
      * @throws IOException IOException
      */
-    public String requestJson(final String url, final String json,
+    public Response requestJson(final String url, final String json,
         final Map<String, String> header) throws IOException {
-        RequestBody body = RequestBody.create(MEDIA_TYPE_JSON, json);
+        RequestBody body = RequestBody.create(okhttp3.MediaType.parse(MediaType.APPLICATION_JSON_VALUE), json);
```
Comment (moremind) [inline shenyu-admin/src/main/java/org/apache/shenyu/admin/utils/HttpUtils.java:220]: remove this package

**Review by moremind — CHANGES_REQUESTED** [review]

File: shenyu-admin/src/main/java/org/apache/shenyu/admin/utils/HttpUtils.java [hunk 2]
```diff
@@ -375,6 +376,15 @@ private void addHeader(final Request.Builder builder, final Map<String, String>
         }
     }
 
+    private boolean isJsonRequest(final Map<String, String> headers) {
+        try {
+            return MEDIA_TYPE_JSON.equals(MediaType.parse(headers.get("Content-Type")));
+        } catch (Exception e) {
+            System.err.println(e);
```
Comment (moremind) [inline shenyu-admin/src/main/java/org/apache/shenyu/admin/utils/HttpUtils.java:383]:
```java
log.error("parse http client json request error=", e);
return false;
```

**Review by moremind — CHANGES_REQUESTED** [review]

**Review by moremind — APPROVED** [review]

File: shenyu-admin/src/main/java/org/apache/shenyu/admin/utils/HttpUtils.java [hunk 3]
```diff
@@ -375,6 +381,15 @@ private void addHeader(final Request.Builder builder, final Map<String, String>
         }
     }
 
+    private boolean isJsonRequest(final Map<String, String> headers) {
+        try {
+            return MEDIA_TYPE_JSON.equals(MediaType.parse(headers.get("Content-Type")));
```
Comment (dengliming) [inline shenyu-admin/src/main/java/org/apache/shenyu/admin/utils/HttpUtils.java:386]: Is this still true if the `Content-Type` header is `application/json`?

**Review by moremind — APPROVED** [review]

**Review by moremind — APPROVED** [review]
