### PR TITLE
[ISSUE #4059] optimize request timeout response

### LINKED ISSUE #4059: [Question] When the proxy service is offline or times out, the shenyugateway reports exception 500
### Question

shenyu version: 2.5.0

shenyu-examples-http
Request:
POST http://localhost:9195/http/shenyu/client/timeout
Accept: application/json
Content-Type: application/json

Response:
{
  "code": 500,
  "message": "Internal Server Error"
}
image

**when random Strategy is  current or failover then Response code 500
Should a more friendly prompt be returned**

### PR DESCRIPTION
**Pull request by moremind**
Fixes #4059 

Make sure that:

- [ ] You have read the [contribution guidelines](https://shenyu.apache.org/community/contributor-guide).
- [ ] You submit test cases (unit or integration tests) that back your changes.
- [ ] Your local test passed `./mvnw clean install -Dmaven.javadoc.skip=true`.

### CODE REVIEW

File: shenyu-plugin/shenyu-plugin-httpclient/src/main/java/org/apache/shenyu/plugin/httpclient/exception/ShenyuTimeoutException.java [hunk 1]
```diff
@@ -0,0 +1,55 @@
...
+ * limitations under the License.
+ */
+
+package org.apache.shenyu.plugin.httpclient.exception;
+
+
+/**
+ * Shenyu request timeout exception.
+ */
+public final class ShenyuTimeoutException extends RuntimeException {
```
Comment (dragon-zhang) [inline shenyu-plugin/shenyu-plugin-httpclient/src/main/java/org/apache/shenyu/plugin/httpclient/exception/ShenyuTimeoutException.java:24]: Maybe it's better to inherit `org.apache.shenyu.common.exception.ShenyuException` ?

Comment (moremind) [reply shenyu-plugin/shenyu-plugin-httpclient/src/main/java/org/apache/shenyu/plugin/httpclient/exception/ShenyuTimeoutException.java:24]: I have thought about it, but the above code throws ShenyuException.

Comment (dragon-zhang) [reply shenyu-plugin/shenyu-plugin-httpclient/src/main/java/org/apache/shenyu/plugin/httpclient/exception/ShenyuTimeoutException.java:24]: ok

**Review by dragon-zhang — APPROVED** [review]
