### PR TITLE
[type:bugfix]Add more retry strategies

### LINKED ISSUE #5920: [Question] <title> 网关向下游下发请求失败时，基于Reactor响应式流实现单机版本的异步非阻塞重试策略
### Question

**Divide或HTTP Client插件中，向下游服务发送请求失败后的重试策略，当前实现方案是比较简单的，建议基于Reactor响应式流实现单机版本的异步非阻塞重试策略。**

实现效果：
● 异步非阻塞，不影响主线程
● 支持自定义重试次数、重试间隔、重试上限
● 支持按任务失败条件出发重试（eg： 指定异常重试）
● 支持异步获取任务执行结果，直到重试成功或者重试超限
● 轻量级，不依赖第三方重试调度中间件(如MQ，ScheduleX)，不依赖Spring框架本身提供的定时调度能力。
● 多种重试策略：自定义策略(自定义退避序列)、固定间隔重试策略、默认重试策略等。

## 当前失败重试代码如下

Image

如图所示，这里是For循环3次比较简单的失败重试。

## 基于Reactor响应式流实现单机版本的异步非阻塞重试策略

实现示例代码如下：

### RetryUtils 工具类
```java
/**
 * 重试工具类
 */
public class RetryUtils {

    /**
     * 记录重试次数
     */
    private static final AtomicInteger retryCount = new AtomicInteger(0);

    /**
     * 执行并返回响应流
     */
    public static Mono<String> execute(Object... param) {
        return execute(RetryBackoffSpecEnum.DEFAULT_BACKOFF, param);
    }

    /**
     * 执行并返回响应流(指定重试策略)
     */
    public static Mono<String> execute(
                  RetryBackoffSpecEnum backoffSpecEnum, Object... param) {
        return retryWithBackoff(doExecute(param), backoffSpecEnum);
    }

    private static Mono<String> doExecute(Object... param) {
        return Mono.defer(() -> {
            // 模拟50%的异常情况，指定异常重试
            if (Math.random() < 0.5) {
                return Mono.error(new IllegalStateException("执行失败... " + Arrays.toString(param)));
            } else {
                return Mono.just("执行成功: " + Arrays.toString(param));
            }
        });
    }

    /**
     * @param mono 需要重试的操作
     * @return 返回包含重试结果的Mono
     */
    public static <T> Mono<T> retryWithBackoff(Mono<T> mono, RetryBackoffSpecEnum backoffSpecEnum) {
        RetryBackoffSpec backoffSpec = holders.get(backoffSpecEnum);

        return mono.doOnNext(i -> System.out.println("Processing item: " + i))
                .doOnError(e -> System.err.println("Error occurred: " + e.getMessage()))
                .retryWhen(
                        backoffSpec.doAfterRetry(retrySignal -> doRetry())
                )
                .doFinally(signalType -> {
                    if (signalType == SignalType.ON_ERROR) {
                        System.err.println("重试结束，最终失败");
                    } else if (signalType == SignalType.ON_COMPLETE) {
                        System.out.println("重试结束，成功完成");
                    }
                    resetRetryCount();
                });
    }

    public enum RetryBackoffSpecEnum {
        /**
         * 默认重试
         */
        DEFAULT_BACKOFF,

        /**
         * 固定重试
         */
        FIXED_BACKOFF,

        /**
         * 自定义重试
         */
        CUSTOM_BACKOFF,
    }

    private static final Map<RetryBackoffSpecEnum, RetryBackoffSpec> holders = new HashMap<>();

    static {
        holders.put(RetryBackoffSpecEnum.DEFAULT_BACKOFF, initDefaultBackoff());
        holders.put(RetryBackoffSpecEnum.FIXED_BACKOFF, initFixedBackoff());
        holders.put(RetryBackoffSpecEnum.CUSTOM_BACKOFF, initCustomBackoff());
    }

    private static RetryBackoffSpec initCustomBackoff() {
        // TODO 自己实现
        return null;
    }

    private static RetryBackoffSpec initFixedBackoff() {
        return Retry.fixedDelay(5, Duration.ofSeconds(2));
    }

    private static RetryBackoffSpec initDefaultBackoff() {
        return Retry.backoff(3, Duration.ofMillis(500))
                .maxBackoff(Duration.ofSeconds(5))
                // 只对瞬时错误进行重试
                .transientErrors(true)
                // 添加 50% 的随机抖动到每次重试的延迟时间
                .jitter(0.5d)
                .filter(t -> t instanceof IllegalStateException)
                // 当达到最大重试次数后抛出一个指定的异常
                .onRetryExhaustedThrow((retryBackoffSpecErr, retrySignal) -> {
                    throw new IllegalStateException("重试超限");
                });
    }

    private static void doRetry() {
        retryCount.incrementAndGet();
        System.out.println("执行重试，重试次数: " + retryCount.get());
    }

    private static void resetRetryCount() {
        retryCount.set(0);
    }
}

```

### 测试重试效果

```java
public static void main(String[] args) {

    for (int i = 1; i <= 20; i++) {
        Mono<String> result = RetryUtils.execute(String.format("第【%s】次调用", i));
        // 订阅结果
        result.subscribe(
                // 成功时处理结果
                data -> System.out.println("Received: " + data),
                // 所有重试都失败时处理错误
                error -> System.err.println("Final error: " + error.getMessage()),
                // 流完成时调用
                () -> System.out.println("Completed")
        );
        try {
            Thread.sleep(10000); // 给异步任务一点时间完成
            System.out.println("===========================分隔符===========================");
        } catch (InterruptedException ignored) {
        }
    }
}
```
使用默认重试策略时，命中IllegalStateException异常规则，重试间隔500ms，最失败大重试3次，如果重试过程中成功，则直接终止重试。

● CASE1 第一次请求成功，不再触发重试：

Image

● CASE2 首次请求执行失败，触发重试，并重试成功，终止重试：

Image

● CASE3 首次请求执行失败，触发重试，重试次数达到上限，终止重试：

Image

### PR DESCRIPTION
**Pull request by JerryDtj**
修复了#5920,保持原有代码不变的基础上,重构了AbstractHttpClientPlugin.让它支持更多的重试策略
Fixes #5920 ,On the basis of keeping the original code unchanged, we refactored AbstractFHIR Plugin Enable it to support more retry strategies

Make sure that:

- [x] You have read the [contribution guidelines](https://shenyu.apache.org/community/contributor-guide).
- [x] You submit test cases (unit or integration tests) that back your changes.
- [x] Your local test passed `./mvnw clean install -Dmaven.javadoc.skip=true`.

### CODE REVIEW

File: shenyu-common/src/main/java/org/apache/shenyu/common/constant/Constants.java [hunk 1]
```diff
@@ -960,7 +960,11 @@ public interface Constants {
      * The constant Content-Encoding.
      */
     String CONTENT_ENCODING = "Content-Encoding";
-    
+    /**
+     * http请求重试策略  http request retry policy.
```
Comment (Aias00) [inline shenyu-common/src/main/java/org/apache/shenyu/common/constant/Constants.java:964]: use English, pls

File: shenyu-common/src/main/java/org/apache/shenyu/common/enums/HttpRetryBackoffSpecEnum.java [hunk 2]
```diff
@@ -0,0 +1,68 @@
...
+
+import java.util.Arrays;
+
+/**
+ * The http scheme enum.
+ */
+public enum HttpRetryBackoffSpecEnum {
+
+    /**
+     * 默认重试.
```
Comment (Aias00) [inline shenyu-common/src/main/java/org/apache/shenyu/common/enums/HttpRetryBackoffSpecEnum.java:28]: use English, pls

File: shenyu-common/src/main/java/org/apache/shenyu/common/enums/HttpRetryBackoffSpecEnum.java [hunk 3]
```diff
@@ -0,0 +1,68 @@
...
+     */
+    DEFAULT_BACKOFF("default"),
+
+    /**
+     * 固定重试.
```
Comment (Aias00) [inline shenyu-common/src/main/java/org/apache/shenyu/common/enums/HttpRetryBackoffSpecEnum.java:33]: use English, pls

File: shenyu-common/src/main/java/org/apache/shenyu/common/enums/HttpRetryBackoffSpecEnum.java [hunk 4]
```diff
@@ -0,0 +1,68 @@
...
+     */
+    FIXED_BACKOFF("fixed"),
+
+    /**
+     * 指数重试.
```
Comment (Aias00) [inline shenyu-common/src/main/java/org/apache/shenyu/common/enums/HttpRetryBackoffSpecEnum.java:38]: use English, pls

File: shenyu-common/src/main/java/org/apache/shenyu/common/enums/HttpRetryBackoffSpecEnum.java [hunk 5]
```diff
@@ -0,0 +1,68 @@
...
+     */
+    EXPONENTIAL_BACKOFF("exponential"),
+
+    /**
+     * 自定义重试.
```
Comment (Aias00) [inline shenyu-common/src/main/java/org/apache/shenyu/common/enums/HttpRetryBackoffSpecEnum.java:43]: use English, pls

File: shenyu-plugin/shenyu-plugin-httpclient/src/main/java/org/apache/shenyu/plugin/httpclient/AbstractHttpClientPlugin.java [hunk 6]
```diff
@@ -88,80 +73,31 @@ public final Mono<Void> execute(final ServerWebExchange exchange, final ShenyuPl
...
-                    .onRetryExhaustedThrow((retryBackoffSpecErr, retrySignal) -> {
-                        throw new ShenyuTimeoutException("Request timeout, the maximum number of retry times has been exceeded");
-                    });
-            return response.retryWhen(retryBackoffSpec)
-                    .onErrorMap(ShenyuTimeoutException.class, th -> new ResponseStatusException(HttpStatus.REQUEST_TIMEOUT, th.getMessage(), th))
-                    .onErrorMap(TimeoutException.class, th -> new ResponseStatusException(HttpStatus.GATEWAY_TIMEOUT, th.getMessage(), th))
-                    .flatMap((Function<Object, Mono<? extends Void>>) o -> chain.execute(exchange));
+
+        RetryStrategy<R> strategy;
+        //这里走配置文件是不是更好点?   Is it better to go with the configuration file here?
```
Comment (Aias00) [inline shenyu-plugin/shenyu-plugin-httpclient/src/main/java/org/apache/shenyu/plugin/httpclient/AbstractHttpClientPlugin.java:78]: use English, pls

File: shenyu-plugin/shenyu-plugin-httpclient/src/main/java/org/apache/shenyu/plugin/httpclient/CustomRetryStrategy.java [hunk 7]
```diff
@@ -0,0 +1,37 @@
...
+
+import org.slf4j.Logger;
+import org.slf4j.LoggerFactory;
+import org.springframework.web.server.ServerWebExchange;
+import reactor.core.publisher.Mono;
+
+import java.time.Duration;
+
+/**
+ * 自定义重试策略 Custom retry policy
```
Comment (Aias00) [inline shenyu-plugin/shenyu-plugin-httpclient/src/main/java/org/apache/shenyu/plugin/httpclient/CustomRetryStrategy.java:11]: use English, pls

File: shenyu-plugin/shenyu-plugin-httpclient/src/main/java/org/apache/shenyu/plugin/httpclient/CustomRetryStrategy.java [hunk 8]
```diff
@@ -0,0 +1,37 @@
...
+ *      还请自己实现
```
Comment (Aias00) [inline shenyu-plugin/shenyu-plugin-httpclient/src/main/java/org/apache/shenyu/plugin/httpclient/CustomRetryStrategy.java:12]: use English, pls

File: shenyu-plugin/shenyu-plugin-httpclient/src/main/java/org/apache/shenyu/plugin/httpclient/CustomRetryStrategy.java [hunk 9]
```diff
@@ -0,0 +1,37 @@
...
+    private final AbstractHttpClientPlugin<R> httpClientPlugin;
+
+    private static final Logger LOG = LoggerFactory.getLogger(CustomRetryStrategy.class);
+
+    public CustomRetryStrategy(AbstractHttpClientPlugin<R> httpClientPlugin) {
+        this.httpClientPlugin = httpClientPlugin;
+    }
+
+    /**
+     * 自定义重试策略 Custom retry policy
```
Comment (Aias00) [inline shenyu-plugin/shenyu-plugin-httpclient/src/main/java/org/apache/shenyu/plugin/httpclient/CustomRetryStrategy.java:26]: use English, pls

File: shenyu-plugin/shenyu-plugin-httpclient/src/main/java/org/apache/shenyu/plugin/httpclient/CustomRetryStrategy.java [hunk 10]
```diff
@@ -0,0 +1,37 @@
...
+     *
+     * @param response   响应的 Mono 对象 The Mono object of the response
+     * @param exchange   当前服务器交换对象 Current Server Exchange Object
+     * @param duration   超时时间 Timeout
+     * @param retryTimes 重试次数 Number of retries
+     * @return 经过重试处理后的响应 Mono 对象 Response Mono object after retry processing
```
Comment (Aias00) [inline shenyu-plugin/shenyu-plugin-httpclient/src/main/java/org/apache/shenyu/plugin/httpclient/CustomRetryStrategy.java:32]: use English, pls

File: shenyu-plugin/shenyu-plugin-httpclient/src/main/java/org/apache/shenyu/plugin/httpclient/DefaultRetryStrategy.java [hunk 11]
```diff
@@ -0,0 +1,117 @@
...
+
+import java.net.URI;
+import java.time.Duration;
+import java.util.*;
+import java.util.concurrent.TimeoutException;
+import java.util.stream.Collectors;
+
+
+/**
+ * 默认重试策略类 Default Retry Policy Class
```
Comment (Aias00) [inline shenyu-plugin/shenyu-plugin-httpclient/src/main/java/org/apache/shenyu/plugin/httpclient/DefaultRetryStrategy.java:28]: use English, pls

File: shenyu-plugin/shenyu-plugin-httpclient/src/main/java/org/apache/shenyu/plugin/httpclient/ExponentialRetryBackoffStrategy.java [hunk 12]
```diff
@@ -0,0 +1,54 @@
...
+    private static final Logger LOG = LoggerFactory.getLogger(ExponentialRetryBackoffStrategy.class);
+
+    private final AbstractHttpClientPlugin<R> httpClientPlugin;
+
+    public ExponentialRetryBackoffStrategy(AbstractHttpClientPlugin<R> httpClientPlugin) {
+        this.httpClientPlugin = httpClientPlugin;
+    }
+
+    /**
+     * 执行重试策略
```
Comment (Aias00) [inline shenyu-plugin/shenyu-plugin-httpclient/src/main/java/org/apache/shenyu/plugin/httpclient/ExponentialRetryBackoffStrategy.java:26]: use English, pls

File: shenyu-plugin/shenyu-plugin-httpclient/src/main/java/org/apache/shenyu/plugin/httpclient/FixedRetryStrategy.java [hunk 13]
```diff
@@ -0,0 +1,43 @@
...
+    private static final Logger LOG = LoggerFactory.getLogger(FixedRetryStrategy.class);
+
+    private final AbstractHttpClientPlugin<R> httpClientPlugin;
+
+    public FixedRetryStrategy(AbstractHttpClientPlugin<R> httpClientPlugin) {
+        this.httpClientPlugin = httpClientPlugin;
+    }
+
+    /**
+     * 执行重试策略
```
Comment (Aias00) [inline shenyu-plugin/shenyu-plugin-httpclient/src/main/java/org/apache/shenyu/plugin/httpclient/FixedRetryStrategy.java:25]: use English, pls

File: shenyu-plugin/shenyu-plugin-httpclient/src/main/java/org/apache/shenyu/plugin/httpclient/RetryStrategy.java [hunk 14]
```diff
@@ -0,0 +1,26 @@
+package org.apache.shenyu.plugin.httpclient;
+
+
+import org.springframework.web.server.ServerWebExchange;
+import reactor.core.publisher.Mono;
+
+import java.time.Duration;
+
+/**
+ * 重试策略接口 Retry Policy Interface
```
Comment (Aias00) [inline shenyu-plugin/shenyu-plugin-httpclient/src/main/java/org/apache/shenyu/plugin/httpclient/RetryStrategy.java:10]: use English, pls

File: shenyu-plugin/shenyu-plugin-httpclient/src/test/java/org/apache/shenyu/plugin/httpclient/RetryStrategyTest.java [hunk 15]
```diff
@@ -0,0 +1,86 @@
...
+
+/**
+ * @author Jerry
+ * @Date 2025/3/16 22:46
+ */
+public class RetryStrategyTest{
+
+    @Test
+    void testDefaultRetryBackoffExecute() {
+        // 创建一个模拟的 AbstractHttpClientPlugin
```
Comment (Aias00) [inline shenyu-plugin/shenyu-plugin-httpclient/src/test/java/org/apache/shenyu/plugin/httpclient/RetryStrategyTest.java:20]: use English, pls

**Review by Aias00 — CHANGES_REQUESTED** [review]

File: shenyu-common/src/main/java/org/apache/shenyu/common/constant/Constants.java (hunk 1 above)
Comment (JerryDtj) [reply shenyu-common/src/main/java/org/apache/shenyu/common/constant/Constants.java]: ok,i fix it

**Comment by Aias00** [comment]
fix ci error pls

**Comment by Aias00** [comment]
fix the ci
u should do the checkstyle local, before submit the code

**Comment by JerryDtj** [comment]
> fix the ci u should do the checkstyle local, before submit the code

好的,多谢,版本已经提交

**Review by Aias00 — APPROVED** [review]
LGTM
