### PR TITLE
[type:fix] fix oracle schema.sql

### LINKED ISSUE #6161: [BUG] oracle schema.sql have issues
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

_No response_

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Environment

```markdown
ShenYu version(s):
```

### Debug logs

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by eye-gu**
close #6161 

Make sure that:

- [x] You have read the [contribution guidelines](https://shenyu.apache.org/community/contributor-guide).
- [ ] You submit test cases (unit or integration tests) that back your changes.
- [x] Your local test passed `./mvnw clean install -Dmaven.javadoc.skip=true`.

### CODE REVIEW

File: db/init/oracle/schema.sql [hunk 1]
```diff
@@ -2513,7 +2513,7 @@ create table discovery
 (
     id                VARCHAR2(128) not null,
     name            VARCHAR2(255) not null,
-    level            VARCHAR2(64) not null,
+    "level"            VARCHAR2(64) not null,
```
Comment (Aias00) [inline db/init/oracle/schema.sql]: no quotation marks, should change this field`s name such as descovery_level

File: db/init/oracle/schema.sql [hunk 2]
```diff
@@ -2528,7 +2528,7 @@ comment on column DISCOVERY.id
   is 'primary key id';
 comment on column DISCOVERY.name
   is 'the discovery name';
-comment on column DISCOVERY.level
+comment on column DISCOVERY."level"
```
Comment (Aias00) [inline db/init/oracle/schema.sql]: no quotation marks

File: db/init/oracle/schema.sql [hunk 3]
```diff
@@ -3068,34 +3068,34 @@ comment on column NAMESPACE_USER_REL.date_updated
     is 'update time';
 
 
-INSERT /*+ IGNORE_ROW_ON_DUPKEY_INDEX(resource(id)) */ INTO resource (id, parent_id, title, name, url, component, resource_type, sort, icon, is_leaf, is_route, perms, status) 
+INSERT /*+ IGNORE_ROW_ON_DUPKEY_INDEX(resource(id)) */ INTO "resource" (id, parent_id, title, name, url, component, resource_type, sort, icon, is_leaf, is_route, perms, status)
```
Comment (Aias00) [inline db/init/oracle/schema.sql:3077]: is the table name must with quotation marks?

File: db/init/oracle/schema.sql [hunk 4]
```diff
@@ -3634,19 +3634,19 @@ COMMENT ON COLUMN registry_config.registry_group IS 'group';
...
-INSERT INTO permission (id, role_id, resource_id, date_created, date_updated) VALUES ('1953049887387303903', '1346358560427216896', '1953048313980116902', sysdate, sysdate);
-INSERT INTO permission (id, role_id, resource_id, date_created, date_updated) VALUES ('1953049887387303904', '1346358560427216896', '1953048313980116903', sysdate, sysdate);
-INSERT INTO permission (id, role_id, resource_id, date_created, date_updated) VALUES ('1953049887387303905', '1346358560427216896', '1953048313980116904', sysdate, sysdate);
\ No newline at end of file
+INSERT /*+ IGNORE_ROW_ON_DUPKEY_INDEX(resource(id)) */ INTO "resource" (id, parent_id, title, name, url, component, resource_type, sort, icon, is_leaf, is_route, perms, status, date_created, date_updated)
+VALUES ('1953048313980116900', '1357956838021890048', 'SHENYU.MENU.SYSTEM.MANAGMENT.REGISTRY', 'registry', '/config/registry', 'registry', 1, 7, 'ordered-list', 0, 0, '', 1, to_timestamp('2025-08-06 17:00:00.000', 'YYYY-MM-DD HH24:MI:SS.FF3'), to_timestamp('2025-08-06 17:00:00.000', 'YYYY-MM-DD HH24:MI:SS.FF3'));
```
Comment (Aias00) [inline db/init/oracle/schema.sql:3644]: Are all oracle version support this method to_timestamp?

**Review by Aias00 — CHANGES_REQUESTED** [review]

File: db/init/oracle/schema.sql (hunk 3 above)
Comment (eye-gu) [reply db/init/oracle/schema.sql:3077]: Because 'resource' is a keyword for Oracle

File: db/init/oracle/schema.sql (hunk 4 above)
Comment (eye-gu) [reply db/init/oracle/schema.sql:3644]: Supported starting from Oracle 9i. The field type is timestamp, so it can be assumed that to_timestamp is also supported.

Comment (eye-gu) [reply db/init/oracle/schema.sql:3644]: And the timestamp field before was also insert through this function

File: db/init/oracle/schema.sql (hunk 3 above)
Comment (Aias00) [reply db/init/oracle/schema.sql:3077]: okay

**Review by Aias00 — APPROVED** [review]
